-- Migration script
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('10times.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('1105info.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('1105newsletters.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('5gstore.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('99acres.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('abesofmaine.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('absolute-snow.co.uk', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('activeandfitdirect.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('adidas.in', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ahswarranty.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aiprm.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('airalo.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('airindia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aliexpress.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aloft.ai', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('altais.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('amazon.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('amazon.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('amazonpay.in', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('amctheatres.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('americanexpress.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('amfam.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('anker.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('anthem.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('anthonypresents.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('anthropic.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aol.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('appfolio.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('apple.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('arizent.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ark-funds.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('arkfunds.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('arkinvest.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('asuswebstorage.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('atlassian.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('atthecrossroads.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('augmentcode.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('avail.co', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('avature.net', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('avis.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aws-experience.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('aws.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('bedbathandbeyond.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('bedjet.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('beehiiv.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('bestbuy.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('bing.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('blink.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('blinknetwork.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('breadfinancial.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('builder.io', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('builtin.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('builtinaustin.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('buymeacoffee.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('c21selectgroup.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ca.gov', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('camsmgt.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('canva.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('capcut.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('care.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('careerbuilder.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('carrier.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('carvana.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cbintouch.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ccsend.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cedars-sinai.org', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('certmetrics.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('chargepoint.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('chase.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('chrispessy.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('chugh.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cinemark.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cio.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('circlemedical.co', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('citi.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('citysportsfitness.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('claude.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('clerk.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cloudflare.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cnbc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('columbia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('comcast.net', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('comenity.net', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('conciergeauctions.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('conferencecalltranscripts.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('connectbyamfam.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('content-magazine.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('costco.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cozymaid.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('craigslisasdasdt.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('creditkarma.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('crexi.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('cvs.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('d-id.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('datamaticsrta.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('davivienda.cr', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('deepseek.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('delinea.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dell.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('delta.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('demandforced3.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dice.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('digitalocean.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('digitaltrends.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('discord.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('discoursemail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('discover.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('disneyplus.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dispatch.me', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('disqus.net', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dmpmusicgroup.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('docusign.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dominionenergyaccount.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dominionenergyinfo.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dominos.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('drstephaniebridwell.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('dvcapp.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('e-vanguard.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ebay.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('economictimes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('economictimesnews.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('email-fordpassrewards.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('email-lenovo.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('email-marriott.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('emeraldx.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('emporiaenergy.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('epicpass.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('epicpassmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('epiqpay.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('equitymaster.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('etrade.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('etradefinancial.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('etsy.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('eufylife.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('eventbrite.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('expedia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('expediamail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('explorehidden.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('eyeappts.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('facebookmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('fidelity.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('finviz.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('fleetfeet.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('flightaware.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('flipkart.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('flybayarea.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('fool.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('foolsubs.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ford.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('freelancer.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('fsastore.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('garmin.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('getmunch.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gitguardian.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('github.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gitlab.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('glassdoor.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gmx.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('godaddy.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('goldstar.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('goodbuygear.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('google.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('govdelivery.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('grafana.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('grammarly.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('grandsierraresort.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gravitywrite.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('greentoe.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('groupon.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('guidde.co', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gumloopmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gurufocus.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('gurusofdance.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hallcpallc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('handy.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hashicorp.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hayneedle.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hays.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hdfcbank.net', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('heygen.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hive.co', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hivebritecommunity.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('homedepot.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('homesnap.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hotpads.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hpsmart.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hsabank.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hulumail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('hyundaiauto.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('icicibank.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('iciciprulife.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('icicisecurities.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('iheart.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('imagekit.io', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('indeed.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('indiatimes-mail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('indiatimes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('influitive.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('insidermonkey.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('instacart.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('instagram.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('interactivebrokers-email.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('interactivebrokers.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('intermiles.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('intuit.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('investorshub.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('invideo.io', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ionos.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('iracing.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('itp.net', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('itprotoday.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('itunes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('jobscan.co', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('keymate.ai', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('kfintech.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('kimblegroup.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('kodekloud.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('kw.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lancom.de', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lastpass.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lensa.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('leonardo.ai', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('levi.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lge.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lindy.ai', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('linkedin.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('livingsocial.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lorventech.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lowes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('lyftmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('magicbricks.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('magwc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mailchimpapp.net', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('matterport.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('maxfashion.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('medallia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('medium.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('meetgeek.ai', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('meetup.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('meta.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('microsoft.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('milesformigraine.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('miltongranger.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mint.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('modal.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('moen.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('moneycontrol.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mongodb.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('monterra.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('morganstanley.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('morningsave.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('morningstar.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('moviepass.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mpug.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mufg.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('muzata.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mycslink.org', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('mygoodtape.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nabshow.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('namecheap.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nanalyze.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('narvar.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('neon.tech', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('netflix.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('netvisionresources.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newegg.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newrez-shellpoint.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newrez.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newrezpartners.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newrezservicing.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('newyorktimes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nextdoor.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nfl.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nike.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nobroker.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('notification-naviextras.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('notifications-economictimes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nsdl.co.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nsdl.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nse.co.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nvidia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nyandcompany.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('nytimes.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('oaklandzoo.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('observablehq.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('onedrive.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('onpointwarranty.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('openai.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('opower.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('parts-stocked.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('payback.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('paypal.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('pdffiller.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('peacocktv.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('perfume.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('pge.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('phillip@rate.com', 'email', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('phontabulous.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('pnc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('portainer.io', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('primusglobal.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('propertyware.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('prpsjeans.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('pyquantnews.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('questdiagnostics.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('quora.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('qvcemail.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('rate.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('realscout.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('realtor.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('redditmail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('redfin.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('reelgood.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('releasemyad.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('remitly.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('resolve.io', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('resumeworded.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('reventure.app', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('rh.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ring.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('roboform.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('samsung-mail.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('samsungcloud.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sandisk.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sbcglobal.net', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sbi.co.in', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sceg.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('schwab.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('seekingalpha.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('selecthomewarranty.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('selina.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('setindia.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sevenrooms.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sfciti.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shef.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sheinnotice.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shelly.cloud', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shift.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shoott.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shopifyemail.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shopmoment.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shopperapproved.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shoppersstop.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('shutterfly.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('simplywall.st', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('skyscanner.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('slack.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('slingemail.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('smartrecruiters.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('smcu.org', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sqlmaestros.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sqlservercentral.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sqlskills.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('squareup.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('starz.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('stocktwits.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('stockunlock.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('streamsets.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('stripe.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('subway.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('sutterhealth.org', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('swiggy.in', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tailscale.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('target.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tdameritrade.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('temuemail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tesla.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('thecapsource.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('thekrazycouponlady.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('themoviedb.org', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('thepixelconnection.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('therealestatecpa.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('thumbtack.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tigerdirect.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tikr.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('timeoutdubai.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tipranks.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('topcashback.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tp-link.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('travelzoo.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tripadvisor.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('tripit.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('trustage.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('trustpilotmail.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('turbotenant.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('uber.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ucsf.edu', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('united.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ups.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('usbank.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('usgrpinc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('usps.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ussquash.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vagaro.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vanguard.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vasion.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('venmo.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('veritosolutionsinc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('viator.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vidiq.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vidyo.ai', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('vynedental.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('walgreens.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('wavebroadband.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('webdevsimplified.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('wellsfargo.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('wellsfargoemail.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('willow.tv', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('wondertechlabs.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('x.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('xfinity.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('yelp.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('yotpo.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('yourasianconnection.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('youtube.com', 'domain', 'delete_1d', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zen-makemytrip.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zerorezcolumbia.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zillow.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zillowrentals.com', 'domain', NULL, NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('ziprecruiter.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zlk.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zocdoc.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zohobookings.com', 'domain', 'keep', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zomato.com', 'domain', 'delete', NULL);
INSERT INTO criteria (key_value, key_type, default_action, parent_id) VALUES ('zyngamail.com', 'domain', 'delete', NULL);
GO
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'email.apple.com', 'subdomain', NULL, id FROM criteria WHERE key_value = 'apple.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'insideapple.apple.com', 'subdomain', 'delete', id FROM criteria WHERE key_value = 'apple.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'sc.dominionenergyaccount.com', 'subdomain', 'keep', id FROM criteria WHERE key_value = 'dominionenergyaccount.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'customersc.dominionenergyinfo.com', 'subdomain', 'delete', id FROM criteria WHERE key_value = 'dominionenergyinfo.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'em1.turbotax.intuit.com', 'subdomain', 'delete', id FROM criteria WHERE key_value = 'intuit.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'notify.newrezservicing.com', 'subdomain', NULL, id FROM criteria WHERE key_value = 'newrezservicing.com';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'alerts.sbi.co.in', 'subdomain', 'keep', id FROM criteria WHERE key_value = 'sbi.co.in';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'communications.sbi.co.in', 'subdomain', 'delete', id FROM criteria WHERE key_value = 'sbi.co.in';
INSERT INTO criteria (key_value, key_type, default_action, parent_id) SELECT 'email.venmo.com', 'subdomain', NULL, id FROM criteria WHERE key_value = 'venmo.com';
GO
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'adidas.in';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'NPRM Webinar Reminder' FROM criteria WHERE key_value = 'aloft.ai';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Reminder: Please Sign and Upload Your NDA' FROM criteria WHERE key_value = 'anker.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Your receipt from Anthropic' FROM criteria WHERE key_value = 'anthropic.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Preeti Dua invited' FROM criteria WHERE key_value = 'email.apple.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Get your new iPhone' FROM criteria WHERE key_value = 'email.apple.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'has been updated' FROM criteria WHERE key_value = 'email.apple.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Upcoming changes to Free Bitbucket workspaces' FROM criteria WHERE key_value = 'atlassian.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'KPMG LLP Follow-Up for the Lead Specialist, Databa' FROM criteria WHERE key_value = 'avature.net';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your event is about to start' FROM criteria WHERE key_value = 'aws-experience.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'Important Notification Regarding Your AWS Marketpl' FROM criteria WHERE key_value = 'aws.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'bestbuy.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'order' FROM criteria WHERE key_value = 'capcut.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Service Fully Restored' FROM criteria WHERE key_value = 'carrier.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Important: Your AWS Certification expires on Feb 1' FROM criteria WHERE key_value = 'certmetrics.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Clerk Update – Oct 31, 2025' FROM criteria WHERE key_value = 'clerk.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Clerk Update – Sept 9, 2025' FROM criteria WHERE key_value = 'clerk.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Clerk Update' FROM criteria WHERE key_value = 'clerk.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'Your login token for the Cloudflare dashboard' FROM criteria WHERE key_value = 'cloudflare.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'costco.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'HDFC BANK LTD -  Allotment of Bonus Equity Share(s' FROM criteria WHERE key_value = 'datamaticsrta.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'HDFC Bank Limited -  Initial Public Offering (“IPO' FROM criteria WHERE key_value = 'datamaticsrta.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'You tried signing, so try this' FROM criteria WHERE key_value = 'docusign.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Hi, you''ve signed and sent, bu' FROM criteria WHERE key_value = 'docusign.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Here to Help - Assistance & Energy Savings Availab' FROM criteria WHERE key_value = 'dominionenergyinfo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Preeti, schedule a free meeting with a Vanguard ad' FROM criteria WHERE key_value = 'e-vanguard.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Meet your 2025 savings goals, Preeti' FROM criteria WHERE key_value = 'e-vanguard.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Increase your retirement savings, Preeti' FROM criteria WHERE key_value = 'e-vanguard.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Unloc(k) your potential' FROM criteria WHERE key_value = 'e-vanguard.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'ebay.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'etsy.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'We’ve updated our Terms & Conditions of Sale' FROM criteria WHERE key_value = 'flightaware.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Start selling with a free $499 POS device.' FROM criteria WHERE key_value = 'godaddy.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'goodbuygear.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'order' FROM criteria WHERE key_value = 'google.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your Greentoe Offer - Status Update' FROM criteria WHERE key_value = 'greentoe.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your Greentoe Offer - New Counter Offer' FROM criteria WHERE key_value = 'greentoe.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Greentoe Offer Confirmation' FROM criteria WHERE key_value = 'greentoe.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Important! Please update your Passport with Bank' FROM criteria WHERE key_value = 'hdfcbank.net';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Your Renewal Fixed deposit advice' FROM criteria WHERE key_value = 'hdfcbank.net';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Nominee updation for your ICICI Bank Account' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'ICICI Bank Statement from November 01, 2025 to Nov' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Form 16A (TDS certificate) for the period July 1 t' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'Transaction alert for your' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'GST Invoice For the Month' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'ICICI Bank Statement' FROM criteria WHERE key_value = 'icicibank.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Newsletter' FROM criteria WHERE key_value = 'interactivebrokers-email.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your AI Avatar for free, Create now!' FROM criteria WHERE key_value = 'invideo.io';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'What’s new in Lindy: Autosave and drafts, Gemini 2' FROM criteria WHERE key_value = 'lindy.ai';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'Password Changed' FROM criteria WHERE key_value = 'newrez-shellpoint.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your recurring payment' FROM criteria WHERE key_value = 'newrezservicing.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'Your billing statement' FROM criteria WHERE key_value = 'notify.newrezservicing.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Payment' FROM criteria WHERE key_value = 'pge.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your RoboForm subscription expires soon' FROM criteria WHERE key_value = 'roboform.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'E-account statement for your SBI account(s).' FROM criteria WHERE key_value = 'sbi.co.in';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'statement' FROM criteria WHERE key_value = 'schwab.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'OTP for Registration' FROM criteria WHERE key_value = 'setindia.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Order' FROM criteria WHERE key_value = 'shef.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Rate Your' FROM criteria WHERE key_value = 'shopperapproved.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Review Requested' FROM criteria WHERE key_value = 'shopperapproved.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Please review' FROM criteria WHERE key_value = 'shopperapproved.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Slack’s free plan will now include additional secu' FROM criteria WHERE key_value = 'slack.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Reminder: Content older than one year will be dele' FROM criteria WHERE key_value = 'slack.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Your Discount Has Been Applied/Updates to the Term' FROM criteria WHERE key_value = 'starz.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'keep', 'Transaction' FROM criteria WHERE key_value = 'topcashback.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete_1d', 'We Noticed a New Login' FROM criteria WHERE key_value = 'tp-link.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL December 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL November 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL October 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL September 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL August 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'UBL July 2025' FROM criteria WHERE key_value = 'ucsf.edu';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Speed up your study or work routine with a free ye' FROM criteria WHERE key_value = 'venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'What''s new on Venmo?' FROM criteria WHERE key_value = 'venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Coming soon, you can' FROM criteria WHERE key_value = 'venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Preeti dua, discover' FROM criteria WHERE key_value = 'email.venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Psst: See what' FROM criteria WHERE key_value = 'email.venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Here''s how' FROM criteria WHERE key_value = 'email.venmo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Loved it? Share & enjoy 20% off your next order' FROM criteria WHERE key_value = 'yotpo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Don''t forget to write a review and get 20% off' FROM criteria WHERE key_value = 'yotpo.com';
INSERT INTO patterns (criteria_id, action, pattern) SELECT id, 'delete', 'Rental market update for 136 H' FROM criteria WHERE key_value = 'zillowrentals.com';
GO
